// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webApp.Models;

#nullable disable

namespace webApp.Migrations
{
    [DbContext(typeof(UsersContext))]
    partial class UsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("webApp.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Course")
                        .HasColumnType("character varying");

                    b.Property<string>("DateTime")
                        .HasColumnType("character varying");

                    b.Property<string>("FirstName")
                        .HasColumnType("character varying");

                    b.Property<string>("Gradebook")
                        .HasColumnType("character varying");

                    b.Property<string>("Group")
                        .HasColumnType("character varying");

                    b.Property<string>("LastName")
                        .HasColumnType("character varying");

                    b.Property<string>("Patronomic")
                        .HasColumnType("character varying");

                    b.Property<string>("Speciality")
                        .HasColumnType("character varying");

                    b.Property<string>("Specialization")
                        .HasColumnType("character varying");

                    b.Property<string>("StudentCondition")
                        .HasColumnType("character varying");

                    b.Property<string>("TrainingLevel")
                        .HasColumnType("character varying");

                    b.Property<string>("TuitionForm")
                        .HasColumnType("character varying");

                    b.Property<string>("TuitionType")
                        .HasColumnType("character varying");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("webApp.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("DateTime")
                        .HasColumnType("character varying");

                    b.Property<string>("Degree")
                        .HasColumnType("character varying");

                    b.Property<string>("Department")
                        .HasColumnType("character varying");

                    b.Property<string>("FirstName")
                        .HasColumnType("character varying");

                    b.Property<string>("LastName")
                        .HasColumnType("character varying");

                    b.Property<string>("Patronomic")
                        .HasColumnType("character varying");

                    b.Property<string>("Post")
                        .HasColumnType("character varying");

                    b.Property<string>("Title")
                        .HasColumnType("character varying");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("webApp.Models.User", b =>
                {
                    
                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Id")
                        .HasColumnType("character varying");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
